version: '3'
services:
  web_server:
    build: ./Textil_Investigation_DataBase
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
      # - mongodb
    container_name: Textil_Investigation-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./Textil_Investigation_DataBase:/web
    environment:
      - TZ=Europe/Berlin

  database:
    image: yobasystems/alpine-mariadb:10.11.8
    container_name: Textil_Investigation-db
    ports:
      - "2222:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
      - ./Textil_Investigation/data/db/mysql:/var/lib/mysql

  mongodb:
    image: mongo:noble
    container_name: Textil_Investigation-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./Textil_Investigation/data/mongo-data:/data/db